import { Project } from '@/types/portfolio'
import zhuangweiContent from '@/data/zhuangwei-inspection-content.json'

export const projects: Project[] = [
  {
    id: 'jifen-bulletin',
    title: '积分通报自动化系统',
    description: '面向电信政企/商客积分业务的数据处理与通报生成工具，支持5个Excel数据源、13名员工、3支局的自动化汇总与报表输出。',
    category: 'tool',
    tags: ['Python', 'Excel', '自动化'],
    imageUrl: 'https://picsum.photos/seed/jifen-bulletin/800/500',
    githubUrl: '#',
    featured: true,
  },
  {
    id: 'zhuangwei-inspection',
    title: '装维图片质检系统 — 多模态 AI Agent',
    description: '用 LangChain + LangGraph 构建的多模态质检 Agent。StateGraph 编排「规划→检索→执行→验证」流水线，RAG 知识库动态注入判定规则，ChatOpenAI 兼容层统一接入 6 家厂商。人力替代率 90%，质检耗时降低 83%，幻觉率从 20% 优化至 8%。',
    category: 'tool',
    tags: ['LangChain', 'LangGraph', 'RAG', '多模态AI', 'Agent架构'],
    imageUrl: '/images/portfolio/zhuangwei-agent.svg',
    featured: true,
    contentHtml: zhuangweiContent.html,
  },
  {
    id: 'openclaw-ppt',
    title: 'OpenClaw 智能体平台架构PPT',
    description: '面向企业级场景的AI智能体平台架构演示文稿，涵盖AI中枢平台、Agent智能体层、业务应用层、底层算力四层结构。',
    category: 'design',
    tags: ['PPT', 'AI架构', '企业商务'],
    imageUrl: 'https://picsum.photos/seed/openclaw/800/500',
    featured: true,
  },
  {
    id: 'bead-craft',
    title: '拼豆图纸制作网站',
    description: '在线拼豆图纸设计与生成工具，支持图片导入自动转换像素网格、颜色匹配、模板导出等功能。',
    category: 'web',
    tags: ['Next.js', 'Canvas', '设计'],
    imageUrl: 'https://picsum.photos/seed/bead-craft/800/500',
    demoUrl: '#',
    githubUrl: '#',
    featured: false,
  },
  {
    id: 'pixel-card-game',
    title: '像素风卡牌PVE对战游戏',
    description: '基于像素美术风格的卡牌对战游戏，包含完整的PVE战斗系统、卡牌收集养成、回合制策略对战等核心玩法。',
    category: 'web',
    tags: ['TypeScript', 'Canvas', '游戏'],
    imageUrl: 'https://picsum.photos/seed/pixel-card/800/500',
    demoUrl: '#',
    githubUrl: '#',
    featured: false,
  },
  {
    id: 'quality-team-report',
    title: '质量信得过班组申报材料',
    description: '中国电信质量信得过班组申报文档制作，包含大量文本编辑、格式排版、字数统计与内容扩充等工作。',
    category: 'design',
    tags: ['Word', '文档编辑', '格式排版'],
    imageUrl: 'https://picsum.photos/seed/quality-report/800/500',
    featured: false,
  },
  {
    id: 'bidding-extractor',
    title: '图片招标信息提取Skill',
    description: '基于AI的图片招标信息自动提取与表格写入工具，支持图片到腾讯文档的字段映射与追加新行。',
    category: 'other',
    tags: ['AI', 'OCR', '腾讯文档'],
    imageUrl: 'https://picsum.photos/seed/bidding/800/500',
    githubUrl: '#',
    featured: false,
  },
  {
    id: 'personal-blog',
    title: '个人博客',
    description: '基于Next.js 14 App Router构建的个人技术博客，支持深色模式、GSAP动画、代码高亮等特性。',
    category: 'web',
    tags: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://picsum.photos/seed/personal-blog/800/500',
    demoUrl: 'https://blog.example.com',
    githubUrl: 'https://github.com/A22139S/blog',
    featured: true,
  },
]
